apiVersion: batch/v1
kind: Job
metadata:
  name: rally-os-openai-vector-faiss-ootb
spec:
  completions: 1
  template:
    metadata:
      name: rally-os-openai-vector-faiss-ootb
      labels: 
        app: rally-opensearch
    spec:
      restartPolicy: Never
      nodeSelector:
        cloud.google.com/gke-nodepool: rally-nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rally-elasticsearch
            topologyKey: kubernetes.io/hostname
      tolerations:
        - key: "kubernetes.io/arch"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: rally
          image: docker.elastic.co/employees/ugosan/rally-custom:144
          imagePullPolicy: Always
          env:
            - name: HOSTPORT
              value: "os-cluster.default.svc.cluster.local:9200"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: os-cluster-admin-password
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: os-cluster-admin-password
                  key: password
            - name: META
              value: "product:OpenSearch,product-version:OpenSearch-2.14.0,benchmark-run:os-ootb-openai-vector-1"
          args:
            [
              "race",
              "--track-path=/rally/custom_tracks/opensearch/openai_vector",
              "--target-hosts=$(HOSTPORT)",
              "--pipeline=benchmark-only",
              "--user-tags=$(META)",
              "--on-error=abort",
              "--client-options=use_ssl:true,verify_certs:false,basic_auth_user:'$(USERNAME)',basic_auth_password:'$(PASSWORD)'",
              "--challenge=index-and-search",
              "--track-params=number_of_shards:1,vector_space:innerproduct,initial_indexing_ingest_percentage:100,vector_engine_type:faiss,concurrent_segment_search:false"
            ]
          volumeMounts:
            - name: rally-config-volume
              mountPath: "/rally/.rally/rally.ini"
              subPath: "rally.ini"
            - name: rally-base-dir
              mountPath: "/rally/.rally"
            - name: rally-logs
              mountPath: "/rally/.rally/logs"
            - name: rally-tracks-data-os
              mountPath: "/rally-tracks-cache"
          resources:
            requests:
              cpu: "2.1"
            limits:
              cpu: "4"
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: rally-config-volume
          configMap:
            name: rally-config
            items:
              - key: rally.ini
                path: rally.ini
        - name: rally-base-dir
          emptyDir: {}
        - name: rally-logs
          hostPath:
            path: /var/log/rally-logs
            type: DirectoryOrCreate
        - name: rally-tracks-data-os
          persistentVolumeClaim:
            claimName: rally-tracks-data-os
      initContainers:
        - name: permission-fix
          image: busybox
          command: ["sh", "-c"]
          args: ["chmod -R 777 /rally/.rally /rally-tracks-cache /var/log/rally-logs"]
          volumeMounts:
            - mountPath: /rally/.rally
              name: rally-base-dir
            - mountPath: /var/log/rally-logs
              name: rally-logs
            - mountPath: /rally-tracks-cache
              name: rally-tracks-data-os
        - name: cleanup-indices
          image: curlimages/curl:8.7.1
          env:
            - name: HOSTPORT
              value: "os-cluster.default.svc.cluster.local:9200"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: os-cluster-admin-password
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: os-cluster-admin-password
                  key: password
          command: ["sh", "-c"]
          args:
            - |
              curl -k -vv -XDELETE "https://$(USERNAME):$(PASSWORD)@$(HOSTPORT)/vectors" &&
              curl -k -vv -XDELETE "https://$(USERNAME):$(PASSWORD)@$(HOSTPORT)/openai" &&
              curl -k -vv -XDELETE "https://$(USERNAME):$(PASSWORD)@$(HOSTPORT)/cohere" 