apiVersion: batch/v1
kind: Job
metadata:
  name: rally-es-so-vector
spec:
  completions: 10
  template:
    metadata:
      name: rally-es-so-vector
      labels: 
        app: rally-elasticsearch
    spec:
      restartPolicy: Never
      nodeSelector:
        cloud.google.com/gke-nodepool: rally-nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rally-opensearch
            topologyKey: kubernetes.io/hostname
      tolerations:
        - key: "kubernetes.io/arch"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: rally
          image: docker.elastic.co/employees/ugosan/rally-custom:115
          imagePullPolicy: Always
          env:
            - name: HOSTPORT
              value: "es-cluster-es-http:9200"
            - name: USERNAME
              value: "elastic"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-cluster-es-elastic-user
                  key: elastic
            - name: META
              value: "product:Elasticsearch,product-version:Elasticsearch-8.13.0,benchmark-run:vector-1"
          args:
            [
              "race",
              "--track-path=/rally/custom_tracks/elasticsearch/so_vector",
              "--target-hosts=$(HOSTPORT)",
              "--pipeline=benchmark-only",
              "--user-tags=$(META)",
              "--on-error=abort",
              "--client-options=use_ssl:true,verify_certs:false,basic_auth_user:'$(USERNAME)',basic_auth_password:'$(PASSWORD)'",
              "--challenge=index-and-search",
              "--track-params=bulk_indexing_clients:1,bulk_size:200,number_of_shards:1,vector_index_type:hnsw"
            ]
          volumeMounts:
            - name: rally-config-volume
              mountPath: "/rally/.rally/rally.ini"
              subPath: "rally.ini"
            - name: rally-base-dir
              mountPath: "/rally/.rally"
            - name: rally-tracks-data-es
              mountPath: "/rally-tracks-cache"
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: rally-config-volume
          configMap:
            name: rally-config
            items:
              - key: rally.ini
                path: rally.ini
        - name: rally-base-dir
          emptyDir: {}
        - name: rally-tracks-data-es
          persistentVolumeClaim:
            claimName: rally-tracks-data-es
      initContainers:
        - name: permission-fix
          image: busybox
          command: ["sh", "-c"]
          args: ["chmod -R 777 /rally/.rally /rally-tracks-cache"]
          volumeMounts:
            - mountPath: /rally/.rally
              name: rally-base-dir
            - mountPath: /rally-tracks-cache
              name: rally-tracks-data-es
